name: xform
description: A Flutter plugin for easy form building. Built in with textfield types, validation and pagination.
version: 0.3.0
author: Paul Mtali <paul.mtali@techie.com>
homepage: https://github.com/indiepaul/xform

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  validate: ^1.7.0

dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter

flutter:
